/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexion.Conexion;
import static gui.Inventario.conn;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static gui.Inventario.rs;
import static gui.Inventario.st;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author javier
 */
public class IntroducirCliente extends javax.swing.JDialog {

    /**
     * Creates new form IntroducirProducto
     */
    int id = 100;
    int band = 0;
    int pr_id;
    public IntroducirCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        band = 0;
        setLocationRelativeTo(parent);
    }

    public IntroducirCliente(java.awt.Frame parent, boolean modal, String filaVal) {
        super(parent, modal);
        initComponents();
        band = 1;
        setLocationRelativeTo(parent);
        bttnIntro.setText("Actualizar");
        System.out.println(filaVal);
        try {

            rs = st.executeQuery("select * from clientes where customer_id="+filaVal);
            while (rs.next()) {
                //cambiar el valor de cadena a entero
                pr_id = Integer.parseInt(rs.getObject(1).toString()) ;
                txtName.setText(rs.getObject(2).toString());
                txtApell.setText(rs.getObject(3).toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bttnIntro = new javax.swing.JToggleButton();
        combSucu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtApell = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/danipay2.png"))); // NOI18N
        jLabel1.setText("                                         INTRODUCIR CLIENTE");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Nombre de cliente:");

        jLabel3.setText("Sucursal:");

        bttnIntro.setText("Introducir");
        bttnIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnIntroActionPerformed(evt);
            }
        });

        combSucu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal1", "Sucursal2", "Sucursal3" }));

        jLabel4.setText("Apellido de cliente:");

        txtApell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(combSucu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApell)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(bttnIntro)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combSucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnIntro)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnIntroActionPerformed
        // TODO add your handling code here:
        int sucursal;
        int combsel = combSucu.getSelectedIndex();
                if(combsel == 0){
                    sucursal =1;
                }else if(combsel==1){
                    sucursal =2;
                }else{
                    sucursal =3;
                }
        if (band == 0) {
            try {
                Conexion con = new Conexion();
                conn = con.getConexion();
                st = con.sta(st);
                rs = st.executeQuery("SELECT MAX(product_id) + 1 FROM MATERIA");
                rs.next();
                id = Integer.parseInt(rs.getString(1));
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            try {
                Conexion con = new Conexion();
                conn = con.getConexion();
                String sqlinsertar = "{call insertar_clientes(?,?,?)}";
                PreparedStatement psta = conn.prepareStatement(sqlinsertar);
                psta.setString(1, txtName.getText());
                psta.setString(2, txtApell.getText());
                psta.setInt(3, sucursal);
                psta.execute();
                psta.close();
                JOptionPane.showMessageDialog(null, "Registro Guardado Satisfactoriamente");
            } catch (Exception e) {
                System.out.println(e.getCause());
            }
        }else if(band==1){
             try {
                // main miconexion = new main();
                Conexion con = new Conexion();
                conn = con.getConexion();
                String sqlinsertar = "update Clientes set cust_first_name=?, CUST_LAST_NAME=?, SUC_ID=? where customer_id="+pr_id+"";
                PreparedStatement psta = conn.prepareStatement(sqlinsertar);
                psta.setString(1, txtName.getText());
                psta.setString(2, txtApell.getText());
                psta.setInt(3, sucursal);
                psta.execute();
                psta.close();
                JOptionPane.showMessageDialog(null, "Registro Guardado Satisfactoriamente");
            } catch (Exception e) {
                System.out.println(e.getCause());
            }
        }
        dispose();
    }//GEN-LAST:event_bttnIntroActionPerformed

    private void txtApellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IntroducirCliente dialog = new IntroducirCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bttnIntro;
    private javax.swing.JComboBox<String> combSucu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApell;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
